### ISSUE TITLE
Cannot load some .osm files

### ISSUE THREAD

**Issue by GabrielKPl** [vvoovv/blender-osm#33]
Hi, well at first i want to thank you for your addon. I donated today to check 3d capabilities of paid version, but i have a problem in some cases. My .osm files didn't exceed 30MB

In Blender I got this:
```
Traceback (most recent call last):
  File "C:\Users\G\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\blender-osm\__init__.py", line 172, in execute
    self.process()
  File "C:\Users\G\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\blender-osm\__init__.py", line 203, in process
    m.process()
  File "C:\Users\G\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\blender-osm\building\manager.py", line 110, in process
    building = elements[osmId].b
AttributeError: b

location: <unknown location>:-1
```
Here is my file:
[osm.zip](https://github.com/vvoovv/blender-osm/files/601206/osm.zip)

**Comment by vvoovv** [comment]
Please provide a link to your OSM file or try to upload it here. I'll try to fix it as soon as possible

**Comment by vvoovv** [comment]
Sorry i didn't notice it.

**Comment by vvoovv** [comment]
Found the reason for the error: wrong mapping in OSM which the addon doesn't process correctly. I'll try to fix it as soon as possible.

**Comment by vvoovv** [comment]
You should have received a message from gumroad with a link to the bug fix release. Please report if it's ok now.

**Comment by GabrielKPl** [comment]
Thank you for fast response. Didn't get any email form gumroad. I used the first link which i got, and everything works now.
